name: Build, Push, and Deploy Docker Image

on:
  push:
    branches:
      - '**'  # This will trigger on all branches
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Fix Docker socket permissions
      - name: Fix Docker Socket Permissions
        run: sudo chmod 666 /var/run/docker.sock

      # Checkout repository to access the Dockerfile and context
      - name: Checkout repository
        uses: actions/checkout@v3

      # Log in to GitHub Container Registry (ghcr.io)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      # Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/syook-flowise-dev:latest